# Generated by Django 5.1.6 on 2025-02-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fooldal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="szemely",
            name="picture",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
