# Generated by Django 5.1.6 on 2025-03-03 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fooldal", "0002_szemely_picture"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="szemely",
            options={"verbose_name_plural": "Személyek"},
        ),
    ]
